apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}apiserver
  labels:
    app.kubernetes.io/component: apiserver
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiserver.deploy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: apiserver
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "9000"
      labels:
        app.kubernetes.io/component: apiserver
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Release.IsInstall }}
      serviceAccountName: {{ include "chart.resourceNamePrefix" . }}apiserver
      {{- end }}
      initContainers:
        - {{- include "chart.checkDbIsReadyInitContainer" . | nindent 10 }}
        {{- if .Release.IsInstall }}
        - name: check-dbmigrator-run
          {{ $kubeVersion := include "chart.KubernetesVersion" . }}
          {{ $kubectlImageVersion := ternary "1.33" $kubeVersion (semverCompare ">=1.34.0-0" (printf "%s.0" $kubeVersion)) }}
          image: "docker.io/bitnamilegacy/kubectl:{{ $kubectlImageVersion }}"
          imagePullPolicy: IfNotPresent
          command: ['kubectl', 'wait', '--namespace={{ .Release.Namespace }}', '--for=condition=complete', 'job/{{ include "chart.resourceNamePrefix" . }}dbmigrator-install', '--timeout=60s']
        {{- end }}
      containers:
        - name: apiserver
          image: {{ .Values.apiserver.deploy.image.repository }}:{{ .Values.imageTag | default (printf "v%s" .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          volumeMounts:
            - name: apiserver-config
              mountPath: {{ .Values.configDir | quote }}
              readOnly: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.apiserver.deploy.resources | nindent 12 }}
          {{- if .Values.apiserver.deploy.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.apiserver.deploy.livenessProbe | nindent 12}}
          {{- end }}
          {{- if .Values.apiserver.deploy.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.apiserver.deploy.readinessProbe | nindent 12}}
          {{- end }}
          command: ['clomonitor-apiserver', '-c', '{{ .Values.configDir }}/apiserver.yaml']
      volumes:
        - name: apiserver-config
          secret:
            secretName: {{ include "chart.resourceNamePrefix" . }}apiserver-config
