[package]
name = "clomonitor-core"
version = "0.6.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
askalono = "0.4.5"
clap = { version = "3.1.18", features = ["derive"] }
git2 = "0.14.4"
glob = "0.3.0"
graphql_client = { version = "0.10.0", features = ["reqwest"] }
http = "0.2.8"
lazy_static = "1.4.0"
regex = "1.5.6"
reqwest = "0.11.10"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
time = { version = "0.3.9", features = ["parsing", "serde"] }
tokio = { version = "1.18.2", features = ["macros", "process", "rt-multi-thread"] }
tracing = "0.1.34"
which = "4.2.5"

[dev-dependencies]
wiremock = "0.5.12"
